import type { Broadcast } from "@/types";

export const mockBroadcasts: Broadcast[] = [
  {
    id: "bc_1",
    title: "Nova versão do Livepulse disponível",
    message: "Melhoramos o módulo de Metas e adicionamos a Loja de LiveCoins. Confira o que mudou.",
    priority: "info",
    target: "all",
    audience_ids: [],
    status: "sent",
    scheduled_at: null,
    sent_at: new Date(Date.now() - 86400_000 * 2).toISOString(),
    created_at: new Date(Date.now() - 86400_000 * 2).toISOString(),
    reach: 5,
  },
  {
    id: "bc_2",
    title: "Manutenção programada",
    message: "Faremos uma manutenção rápida no dia 20/07 às 03h. Downtime esperado: 15 min.",
    priority: "warning",
    target: "all",
    audience_ids: [],
    status: "scheduled",
    scheduled_at: new Date(Date.now() + 86400_000 * 3).toISOString(),
    sent_at: null,
    created_at: new Date(Date.now() - 3600_000 * 5).toISOString(),
    reach: 5,
  },
  {
    id: "bc_3",
    title: "Plano Scale com 20% off até o fim do mês",
    message: "Upgrade seu plano com desconto exclusivo. Fale com o suporte para ativar.",
    priority: "info",
    target: "selected",
    audience_ids: ["agc_neon_stars", "agc_prisma"],
    status: "sent",
    scheduled_at: null,
    sent_at: new Date(Date.now() - 86400_000 * 7).toISOString(),
    created_at: new Date(Date.now() - 86400_000 * 7).toISOString(),
    reach: 2,
  },
  {
    id: "bc_4",
    title: "Rascunho — Novidades da Temporada 3",
    message: "Ainda estamos finalizando as premiações da Temporada 3 · Prisma.",
    priority: "info",
    target: "all",
    audience_ids: [],
    status: "draft",
    scheduled_at: null,
    sent_at: null,
    created_at: new Date(Date.now() - 3600_000 * 2).toISOString(),
    reach: 0,
  },
];
