import type { Agency, Subscription } from "@/types";

const logo = (seed: string) =>
  `https://api.dicebear.com/9.x/shapes/svg?seed=${encodeURIComponent(seed)}&backgroundType=gradientLinear`;

export const mockAgencies: Agency[] = [
  {
    id: "agc_livepulse_studio",
    name: "Livepulse Studio",
    slug: "livepulse-studio",
    logo_url: logo("Livepulse Studio"),
    country: "BR",
    owner_id: "usr_owner_1",
    status: "active",
    plan: "scale",
    hosts_count: 42,
    managers_count: 4,
    mrr: 1490,
    created_at: "2025-01-10T09:00:00Z",
  },
  {
    id: "agc_neon_stars",
    name: "Neon Stars Agency",
    slug: "neon-stars",
    logo_url: logo("Neon Stars"),
    country: "BR",
    owner_id: "usr_owner_2",
    status: "active",
    plan: "growth",
    hosts_count: 28,
    managers_count: 3,
    mrr: 690,
    created_at: "2025-03-20T09:00:00Z",
  },
  {
    id: "agc_prisma",
    name: "Prisma Live",
    slug: "prisma-live",
    logo_url: logo("Prisma"),
    country: "PT",
    owner_id: "usr_owner_3",
    status: "trial",
    plan: "starter",
    hosts_count: 12,
    managers_count: 1,
    mrr: 0,
    created_at: "2026-06-01T09:00:00Z",
  },
  {
    id: "agc_aurora",
    name: "Aurora Creators",
    slug: "aurora-creators",
    logo_url: logo("Aurora"),
    country: "MX",
    owner_id: "usr_owner_4",
    status: "suspended",
    plan: "growth",
    hosts_count: 18,
    managers_count: 2,
    mrr: 690,
    created_at: "2025-08-14T09:00:00Z",
  },
  {
    id: "agc_horizon",
    name: "Horizon Media",
    slug: "horizon-media",
    logo_url: logo("Horizon"),
    country: "BR",
    owner_id: "usr_owner_5",
    status: "active",
    plan: "enterprise",
    hosts_count: 96,
    managers_count: 9,
    mrr: 3490,
    created_at: "2024-12-05T09:00:00Z",
  },
];

export const mockSubscriptions: Subscription[] = mockAgencies.map((a, i) => ({
  id: `sub_${a.id}`,
  agency_id: a.id,
  plan: a.plan,
  status: a.status,
  price_monthly: a.mrr,
  seats: a.hosts_count + a.managers_count,
  next_invoice_at: new Date(Date.now() + (i + 1) * 86400_000 * 6).toISOString(),
  started_at: a.created_at,
}));
