/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestAgencyRouteImport } from './routes/request-agency'
import { Route as PendingPaymentRouteImport } from './routes/pending-payment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SignupHostRouteImport } from './routes/signup.host'
import { Route as SignupAgencyRouteImport } from './routes/signup.agency'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRankingRouteImport } from './routes/app.ranking'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppManagersRouteImport } from './routes/app.managers'
import { Route as AppInvitesRouteImport } from './routes/app.invites'
import { Route as AppHostsRouteImport } from './routes/app.hosts'
import { Route as AppGoalsRouteImport } from './routes/app.goals'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCommunityRouteImport } from './routes/app.community'
import { Route as AppCommissionsRouteImport } from './routes/app.commissions'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminOverviewRouteImport } from './routes/admin.overview'
import { Route as AdminBroadcastsRouteImport } from './routes/admin.broadcasts'
import { Route as AdminAgenciesRouteImport } from './routes/admin.agencies'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAgencyRoute = RequestAgencyRouteImport.update({
  id: '/request-agency',
  path: '/request-agency',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingPaymentRoute = PendingPaymentRouteImport.update({
  id: '/pending-payment',
  path: '/pending-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SignupHostRoute = SignupHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => SignupRoute,
} as any)
const SignupAgencyRoute = SignupAgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => SignupRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppManagersRoute = AppManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => AppRoute,
} as any)
const AppInvitesRoute = AppInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => AppRoute,
} as any)
const AppHostsRoute = AppHostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppCommissionsRoute = AppCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBroadcastsRoute = AdminBroadcastsRouteImport.update({
  id: '/broadcasts',
  path: '/broadcasts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgenciesRoute = AdminAgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-payment': typeof PendingPaymentRoute
  '/request-agency': typeof RequestAgencyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRouteWithChildren
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/app/ai': typeof AppAiRoute
  '/app/commissions': typeof AppCommissionsRoute
  '/app/community': typeof AppCommunityRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/hosts': typeof AppHostsRoute
  '/app/invites': typeof AppInvitesRoute
  '/app/managers': typeof AppManagersRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/signup/agency': typeof SignupAgencyRoute
  '/signup/host': typeof SignupHostRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-payment': typeof PendingPaymentRoute
  '/request-agency': typeof RequestAgencyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRouteWithChildren
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/app/ai': typeof AppAiRoute
  '/app/commissions': typeof AppCommissionsRoute
  '/app/community': typeof AppCommunityRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/hosts': typeof AppHostsRoute
  '/app/invites': typeof AppInvitesRoute
  '/app/managers': typeof AppManagersRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/signup/agency': typeof SignupAgencyRoute
  '/signup/host': typeof SignupHostRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/confirm-email': typeof ConfirmEmailRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pending-payment': typeof PendingPaymentRoute
  '/request-agency': typeof RequestAgencyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRouteWithChildren
  '/admin/agencies': typeof AdminAgenciesRoute
  '/admin/broadcasts': typeof AdminBroadcastsRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/support': typeof AdminSupportRoute
  '/app/ai': typeof AppAiRoute
  '/app/commissions': typeof AppCommissionsRoute
  '/app/community': typeof AppCommunityRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/hosts': typeof AppHostsRoute
  '/app/invites': typeof AppInvitesRoute
  '/app/managers': typeof AppManagersRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/ranking': typeof AppRankingRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/signup/agency': typeof SignupAgencyRoute
  '/signup/host': typeof SignupHostRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/pending-payment'
    | '/request-agency'
    | '/reset-password'
    | '/signup'
    | '/admin/agencies'
    | '/admin/broadcasts'
    | '/admin/overview'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/app/ai'
    | '/app/commissions'
    | '/app/community'
    | '/app/dashboard'
    | '/app/finance'
    | '/app/goals'
    | '/app/hosts'
    | '/app/invites'
    | '/app/managers'
    | '/app/notifications'
    | '/app/profile'
    | '/app/ranking'
    | '/app/reports'
    | '/app/settings'
    | '/signup/agency'
    | '/signup/host'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/pending-payment'
    | '/request-agency'
    | '/reset-password'
    | '/signup'
    | '/admin/agencies'
    | '/admin/broadcasts'
    | '/admin/overview'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/app/ai'
    | '/app/commissions'
    | '/app/community'
    | '/app/dashboard'
    | '/app/finance'
    | '/app/goals'
    | '/app/hosts'
    | '/app/invites'
    | '/app/managers'
    | '/app/notifications'
    | '/app/profile'
    | '/app/ranking'
    | '/app/reports'
    | '/app/settings'
    | '/signup/agency'
    | '/signup/host'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/pending-payment'
    | '/request-agency'
    | '/reset-password'
    | '/signup'
    | '/admin/agencies'
    | '/admin/broadcasts'
    | '/admin/overview'
    | '/admin/subscriptions'
    | '/admin/support'
    | '/app/ai'
    | '/app/commissions'
    | '/app/community'
    | '/app/dashboard'
    | '/app/finance'
    | '/app/goals'
    | '/app/hosts'
    | '/app/invites'
    | '/app/managers'
    | '/app/notifications'
    | '/app/profile'
    | '/app/ranking'
    | '/app/reports'
    | '/app/settings'
    | '/signup/agency'
    | '/signup/host'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ConfirmEmailRoute: typeof ConfirmEmailRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PendingPaymentRoute: typeof PendingPaymentRoute
  RequestAgencyRoute: typeof RequestAgencyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-agency': {
      id: '/request-agency'
      path: '/request-agency'
      fullPath: '/request-agency'
      preLoaderRoute: typeof RequestAgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-payment': {
      id: '/pending-payment'
      path: '/pending-payment'
      fullPath: '/pending-payment'
      preLoaderRoute: typeof PendingPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email': {
      id: '/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof ConfirmEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/signup/host': {
      id: '/signup/host'
      path: '/host'
      fullPath: '/signup/host'
      preLoaderRoute: typeof SignupHostRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/agency': {
      id: '/signup/agency'
      path: '/agency'
      fullPath: '/signup/agency'
      preLoaderRoute: typeof SignupAgencyRouteImport
      parentRoute: typeof SignupRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ranking': {
      id: '/app/ranking'
      path: '/ranking'
      fullPath: '/app/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/managers': {
      id: '/app/managers'
      path: '/managers'
      fullPath: '/app/managers'
      preLoaderRoute: typeof AppManagersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invites': {
      id: '/app/invites'
      path: '/invites'
      fullPath: '/app/invites'
      preLoaderRoute: typeof AppInvitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hosts': {
      id: '/app/hosts'
      path: '/hosts'
      fullPath: '/app/hosts'
      preLoaderRoute: typeof AppHostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/commissions': {
      id: '/app/commissions'
      path: '/commissions'
      fullPath: '/app/commissions'
      preLoaderRoute: typeof AppCommissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/broadcasts': {
      id: '/admin/broadcasts'
      path: '/broadcasts'
      fullPath: '/admin/broadcasts'
      preLoaderRoute: typeof AdminBroadcastsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agencies': {
      id: '/admin/agencies'
      path: '/agencies'
      fullPath: '/admin/agencies'
      preLoaderRoute: typeof AdminAgenciesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgenciesRoute: typeof AdminAgenciesRoute
  AdminBroadcastsRoute: typeof AdminBroadcastsRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgenciesRoute: AdminAgenciesRoute,
  AdminBroadcastsRoute: AdminBroadcastsRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppCommissionsRoute: typeof AppCommissionsRoute
  AppCommunityRoute: typeof AppCommunityRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppHostsRoute: typeof AppHostsRoute
  AppInvitesRoute: typeof AppInvitesRoute
  AppManagersRoute: typeof AppManagersRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRankingRoute: typeof AppRankingRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppCommissionsRoute: AppCommissionsRoute,
  AppCommunityRoute: AppCommunityRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppHostsRoute: AppHostsRoute,
  AppInvitesRoute: AppInvitesRoute,
  AppManagersRoute: AppManagersRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRankingRoute: AppRankingRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SignupRouteChildren {
  SignupAgencyRoute: typeof SignupAgencyRoute
  SignupHostRoute: typeof SignupHostRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupAgencyRoute: SignupAgencyRoute,
  SignupHostRoute: SignupHostRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ConfirmEmailRoute: ConfirmEmailRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PendingPaymentRoute: PendingPaymentRoute,
  RequestAgencyRoute: RequestAgencyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
